### ISSUE TITLE
Didn't see information from bus

### ISSUE THREAD

**Issue by AjvarXX** [bulletmark/edid-rw#11]
**Newer version of edid-rw did not read EDID from the bus 1, address 50 where it surely exists.**
I used version from 11/23/2015 afterwards which found EDID.

**mint@mint ~/EDID/edid-rw $ sudo bash
mint edid-rw # sudo sensors-detect**
# sensors-detect revision 6284 (2015-05-31 14:00:33 +0200)
# System: Micro-Star International Co., Ltd. GX780R/GT780R/GT780DXR/GT783R (laptop)
# Board: Micro-Star International Co., Ltd. MS-1761
# Kernel: 4.8.0-53-generic x86_64
# Processor: Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz (6/42/7)

This program will help you ...
... 
Lastly, we can probe the I2C/SMBus adapters for connected hardware
monitoring devices. This is the most risky part, and while it works
reasonably well on most systems, it has been reported to cause trouble
on some systems.
Do you want to probe the I2C/SMBus adapters now? (YES/no): **y**
Using driver `i2c-i801' for device 0000:00:1f.3: Intel Cougar Point (PCH)
Module i2c-i801 loaded successfully.
...
Next adapter: nvkm-0000:01:00.0-bus-0001 (i2c-1)
Do you want to scan it? (yes/NO/selectively): n
...
Sorry, no sensors were detected.
This is relatively common on laptops, where thermal management is
handled by ACPI rather than the OS.`
**mint edid-rw # sudo modprobe i2c-i801
mint edid-rw # sudo modprobe i2c-dev
mint edid-rw # sudo i2cdetect -l**
i2c-3	i2c       	nvkm-0000:01:00.0-bus-0005      	I2C adapter
i2c-1	i2c       	nvkm-0000:01:00.0-bus-0001      	I2C adapter
i2c-11	i2c       	nvkm-0000:01:00.0-aux-000d      	I2C adapter
i2c-8	i2c       	nvkm-0000:01:00.0-aux-000a      	I2C adapter
i2c-6	i2c       	nvkm-0000:01:00.0-bus-0008      	I2C adapter
i2c-4	i2c       	nvkm-0000:01:00.0-bus-0006      	I2C adapter
i2c-2	i2c       	nvkm-0000:01:00.0-bus-0002      	I2C adapter
i2c-12	smbus     	SMBus I801 adapter at f000      	SMBus adapter
i2c-0	i2c       	nvkm-0000:01:00.0-bus-0000      	I2C adapter
i2c-9	i2c       	nvkm-0000:01:00.0-aux-000b      	I2C adapter
i2c-10	i2c       	nvkm-0000:01:00.0-aux-000c      	I2C adapter
i2c-7	i2c       	nvkm-0000:01:00.0-bus-0009      	I2C adapter
i2c-5	i2c       	nvkm-0000:01:00.0-bus-0007      	I2C adapter
**mint edid-rw # sudo i2cdump -r 0-127 1 0x50**
No size specified (using byte-data access)
WARNING! This program can confuse your I2C bus, cause data loss and worse!
I will probe file /dev/i2c-1, address 0x50, mode byte
Probe range limited to 0x00-0x7f.
Continue? [Y/n] **y**
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f    0123456789abcdef
00: 00 ff ff ff ff ff ff 00 0d af 20 17 00 00 00 00    ........?? ?....
10: 01 15 01 04 90 26 15 78 1a d8 95 a3 55 4d 9d 27    ?????&?x????UM?'
20: 0f 50 54 00 00 00 01 01 01 01 01 01 01 01 01 01    ?PT...??????????
30: 01 01 01 01 01 01 2e 36 80 a0 70 38 1f 40 30 20    ??????.6??p8?@0 
40: 35 00 e0 0e 11 00 00 18 55 41 80 a0 70 38 25 40    5.???..?UA??p8%@
50: 30 20 35 00 e0 0e 11 00 00 18 cb 4b 80 58 70 38    0 5.???..??K?Xp8
60: 12 40 18 20 35 00 e0 0e 11 00 00 1e 20 56 80 58    ?@? 5.???..? V?X
70: 70 38 12 40 18 20 35 00 e0 0e 11 00 00 1e 00 98    p8?@? 5.???..?.?
**mint edid-rw # sudo i2cdetect 1**
WARNING! This program can confuse your I2C bus, cause data loss and worse!
I will probe file /dev/i2c-1.
I will probe address range 0x03-0x77.
Continue? [Y/n] **y**
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- -- 
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
50: 50 -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
70: -- -- -- -- -- -- -- --                         
**mint edid-rw # sudo ./edid-rw 1 | edid-decode**
Traceback (most recent call last):
  File "./edid-rw", line 131, in <module>
    main()
  File "./edid-rw", line 128, in main
    os.write(sys.stdout.fileno(), array.array('B', edid).tobytes())
AttributeError: 'array.array' object has no attribute 'tobytes'
Extracted contents:
header:          00 00 00 00 00 00 00 00
serial number:   00 00 00 00 00 00 00 00 00 00
version:         00 00
basic params:    00 00 00 00 00
chroma info:     00 00 00 00 00 00 00 00 00 00
established:     00 00 00
standard:        00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
descriptor 1:    00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
descriptor 2:    00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
descriptor 3:    00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
descriptor 4:    00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
extensions:      00
checksum:        00

No header found
Manufacturer: @@@ Model 0 Serial Number 0
EDID version: 0.0
Analog display, Input voltage level: 0.7/0.3 V
Sync: 
Image size is variable
Gamma: 1.00
Monochrome or grayscale display
Established timings supported:
Standard timings supported:
non-conformant standard timing (0 horiz)
non-conformant standard timing (0 horiz)
non-conformant standard timing (0 horiz)
non-conformant standard timing (0 horiz)
non-conformant standard timing (0 horiz)
non-conformant standard timing (0 horiz)
non-conformant standard timing (0 horiz)
non-conformant standard timing (0 horiz)
Manufacturer-specified data, tag 0
Manufacturer-specified data, tag 0
Manufacturer-specified data, tag 0
Manufacturer-specified data, tag 0
Checksum: 0x0 (valid)
EDID block does not conform at all!
	Bad year of manufacture
	Manufacturer name field contains garbage

**Comment by bulletmark** [comment]
Yes, sorry it seems I made a change late last year which only works on Python 3. Given Python 2 is EOL now then I have changed it to always run under Python 3. Please run it again and confirm it works ok now.

**Comment by bulletmark** [comment]
@AjvarXX never replied but closing this as I am sure commit 72ebddfac7aa14f16a814a1b0c8ff4a01c42389f fixes this issue.
