### ISSUE TITLE
Unable to write EDID info to EDID emulator

### ISSUE THREAD

**Issue by DGdB** [bulletmark/edid-rw#15]
Hi Guys,

I have been using this tool to write EDID information to some cheap inline EDID emulators from china. What an amazing tool! I am even using EDID editors to customise the edid.bin and writing it. Works a treat!

Issue is I have received a batch of EDID emulators that have no HDMI audio... This is bad for me as I now have 200 of them and they are almost useless... I tried to re-write the EDID to allow audio (which has worked on other models) and sure enough, it won't write. Anyone got any ideas? It's as if the PC can't see it, except it can?

When I try extract/view EDID info:
`sudo ./edid-rw 3 | edid-decode
Traceback (most recent call last):
  File "./edid-rw", line 137, in <module>
    main()
  File "./edid-rw", line 125, in main
    edid = [dev.read(i) for i in range(EDID_HDR)]
  File "./edid-rw", line 125, in <listcomp>
    edid = [dev.read(i) for i in range(EDID_HDR)]
  File "./edid-rw", line 51, in read
    return self.smb.read_byte_data(EDID_ADDR, n)
OSError: [Errno 6] No such device or address
EDID extract of 'stdin' failed`

When I try to write EDID info:
`sudo ./edid-rw -w 3 <modi-edid.bin
Traceback (most recent call last):
  File "./edid-rw", line 137, in <module>
    main()
  File "./edid-rw", line 121, in main
    dev.write(i, val)
  File "./edid-rw", line 55, in write
    self.smb.write_byte_data(EDID_ADDR, n, val)
OSError: [Errno 6] No such device or address`

When I try grab EDID info using read-edid:
`sudo get-edid | parse-edid
This is read-edid version 3.0.2. Prepare for some fun.
Attempting to use i2c interface
No EDID on bus 0
No EDID on bus 1

No EDID on bus 2
No EDID on bus 4
No EDID on bus 5
No EDID on bus 6
1 potential busses found: 3
256-byte EDID successfully retrieved from i2c bus 3
Looks like i2c was successful. Have a good day.
You seem to have too many extension blocks. Will not continue to parse
Something strange happened. Please contact the author,
Matthew Kern at <pyrophobicman@gmail.com>`

Any help is appreciated! I know this tool was unsupported just shy of a month ago so if no help is available that's OK too... This same EDID emulator has worked before with your tool, but I suspect the EDID flashed to these by the manufacturer is corrupt or something else weird? Any idea how to force write EDID or reset the EDID or something?

I have already tried the variant of the tool spoken of here: #3

**Comment by mssuleiman** [comment]
hi 
did you had any luck , I am facing the same problem tried all the possible ways but with no luck .

**Comment by DGdB** [comment]
> hi 
> did you had any luck , I am facing the same problem tried all the possible ways but with no luck .

I didn't. Some devices are just EDID locked and you can't really do much about it. We use enough of these things that I ordered a bunch and got the manufacturer to write a custom EDID for me... Best of luck!
