### ISSUE TITLE
"[Errno 6] No such device or address" when trying to write EDID

### ISSUE THREAD

**Issue by Bozzeye** [bulletmark/edid-rw#3]
I am trying to update the EDID information on an HDMI adapter from Chalkboard Electronics. The operating system is Ubuntu 14.04 LTS running live on a USB stick.

This is what I get when reading:
`ubuntu@ubuntu:~/edid-rw$ sudo ./edid-rw 6 | edid-decode`

> Extracted contents:
> header:          00 ff ff ff ff ff ff 00
> serial number:   30 e4 45 03 00 00 00 00 00 15
> version:         01 04
> basic params:    90 16 0e 78 02
> chroma info:     e8 87 96 5a 55 95 28 22 51 55
> established:     00 00 00
> standard:        01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01
> descriptor 1:    4c 1d 00 ec 50 20 18 30 40 30 57 00 d9 88 00 00 00 1b
> descriptor 2:    16 12 00 80 50 20 16 30 30 20 47 00 d9 88 00 00 00 1b
> descriptor 3:    00 00 00 fe 00 43 33 47 52 4e 80 31 30 31 57 58 31 0a
> descriptor 4:    00 00 00 00 00 00 41 32 a8 00 00 00 00 01 01 0a 20 20
> extensions:      00
> checksum:        9a
> 
> Manufacturer: LGD Model 345 Serial Number 0
> Made week 0 of 2011
> EDID version: 1.4
> Digital display
> 6 bits per primary color channel
> Digital interface is not defined
> Maximum image size: 22 cm x 14 cm
> Gamma: 2.20
> Supported color formats: RGB 4:4:4
> First detailed timing is preferred timing
> Established timings supported:
> Standard timings supported:
> Detailed mode: Clock 75.000 MHz, 217 mm x 136 mm
>                1280 1344 1392 1516 hborder 0
>                 800  805  812  824 vborder 0
>                +hsync -vsync
> Detailed mode: Clock 46.300 MHz, 217 mm x 136 mm
>                1280 1328 1360 1408 hborder 0
>                 800  804  811  822 vborder 0
>                +hsync -vsync
> ASCII string: C3GRN�101WX1
> Manufacturer-specified data, tag 0
> Checksum: 0x9a
> EDID block does NOT conform to EDID 1.3!
>     Missing name descriptor
>     Missing monitor ranges`

This is what I get when trying to update:
`ubuntu@ubuntu:~/edid-rw$ sudo ./edid-rw -w 6 <edid_auo14.bin`

> Traceback (most recent call last):
>   File "./edid-rw", line 141, in <module>
>     main()
>   File "./edid-rw", line 125, in main
>     dev.write(i, val)
>   File "./edid-rw", line 52, in write
>     self.smb.write_byte_data(EDID_ADDR, n, val)
> IOError: [Errno 6] No such device or address

Edit: I have tried with Ubuntu 14.04 and 13.10. I have tried on a Lenovo IdeaPad Y510p and a desktop computer with a Gigabyte GA-Z77-D3H motherboard. The error is all the same.

**Comment by CoffeeColombia** [comment]
Hi
I bought an HDMI to LVDS coverter to connect an Orange Pie Plus 2 with a ” LCD (15 inches) LG LP156WH4″ with a resolution 1366×768 60 Hz, Fclk 70Mhz. I need to program this chalkboard device but, I have not the binary file to configure it. How can I generate the binary file "edid_auo14.bin" with these parameters?

Thank’s

Best Regards

**Comment by ChalkElec** [comment]
Hello,

Please, find EDID file for 1366x768 attached.

**Comment by CoffeeColombia** [comment]
Thank's for your support , I tested the file"edid_auo14.bin" but didn't work with the LCD;

LCD receives RGB666 format and a different fclk = 70 MHZ . 
this is the modeline with the LCD parameters :  Modeline "1366x768"   70   1366 1402 1450 1492   768 771 776 782  +hsync +vsync;

 how can I generate a file .bin  with this parameters or others resolutions by example "1360x768", "1368x768", etc ?

thanks

**Comment by bulletmark** [comment]
Should move this issue to the @ChalkElec github repo.
