### ISSUE TITLE
Write 256 Bytes

### ISSUE THREAD

**Issue by BrianKMcKinnon** [bulletmark/edid-rw#4]
Hey, great work on this. I have one issue though, I'm trying to write 256 Bytes, and it stops after 128. Is there an argument I can use to include block 2? I haven't found one in the readme, but it looks like you've done something to include 256 bytes in the source code.

**Comment by bulletmark** [comment]
This utility was originally written by me for edid version 1 which is 128 bytes. Later, on request, I added the capability to read/write edid version 2 which is 256 bytes. The version is defined in the header of the first 128 byte block. The program reads and writes the length based on that version field.

**Comment by BrianKMcKinnon** [comment]
I found my problem. I was using the wrong EDID bin file. Sorry for the
mistake! Great job on this!
