### ISSUE TITLE
It's not your fault, but I broke my PC. Any advice?

### ISSUE THREAD

**Issue by Taiiwo** [bulletmark/edid-rw#5]
So I used this utility on a device that was not my monitor. My PC now will not boot. It turns on, the HDD light flickers a few times, but then stops. Nothing displays on the monitor, however I can use a raspberry pi on the same screen so I know it's not the screen. I replaced the graphics card, and still no luck, so I fear I may have written to some device on my motherboard? My only other thoughts are that I've written to a fan speed or temperature sensor, which I am aware are sometimes i2c devices.

My motherboard is an m5a97 pro. My OS is Manjaro Linux. If you need any other information, please ask.

**Comment by bulletmark** [comment]
Gee, very sorry to hear this. Can you boot to BIOS? If your motherboard is making a series of beeps then look that up on Google to possibly find what the beep sequence may mean.

**Comment by Taiiwo** [comment]
Nope. No bios. I've tried  VGA, DVI, and HDMI connection. Due to the lack of HDD lights blinking, I'm almost positive that I've overwritten some device that's required for the motherboard to boot. I was looking for anyone with knowledge of which I2C device I might have overwritten. It's looking like I might just have to buy a new motherboard.

**Comment by bulletmark** [comment]
I added extra warnings in the README with commit 3215e49ae0ad67064862efbaecff7f7b098a839f.

**Comment by kerberos20** [comment]
hi, i had recently same issue, flashed i2c-0 which was obviously wrong and my laptop ended up broken
after 2 days of googling i founded what did i broke
i flashed edid into one of my ram modules xD
maybe its your issue too

**Comment by Taiiwo** [comment]
I'm so sorry for not posting this sooner, but it was in fact a RAM module. I shipped it back, as ripjaws come with a lifetime warranty. Quick fix: Just remove each module one at a time until it works, then replace the broken module.

Again, sorry for not posting my found solution. I hate it when people leave threads like this.

**Comment by kerberos20** [comment]
well that ram is not broken it just missing serial presence detect (SPD), but it can be reflashed.
heres what i did: started pc without that broken ram, in grub set badram to that amount of your working ram, than sleep pc in s3 (suspend to ram) and put broken ram inside, start pc
and now u just need to fix that ram.
dump SPD from any other working ram, doesnt mather which one, as long it is working one.
ram has reserved 0x50 - 0x57 registers on smbus, shouldnt be hard to find it
once u flash ur broken ram, that u just need to fix timings and few other stuffs
most of it isd just stick name and bunch of unnecesary stuffs
only thing u need to change is: bit 0x04 up to 0x07, timings itself will work under jedec
http://www.simmtester.com/page/news/showpubnews.asp?num=153 here u can see what to set.
values for your ram u can find in datasheet or serial presence detect manuals for your modules, not hard to find
