### ISSUE TITLE
Your script saved one of my HDMI ports

### ISSUE THREAD

**Issue by Quad5Ny** [bulletmark/edid-rw#7]
I was flashing on of the HDMI ports on my 4K display to default to 3840x2160* and for some reason **ChalkElec's script only writes 128bytes**.  The port still worked but I was getting digital sparkles (colored random dots) all over the screen, and it was having a hard time negotiating above 300MHz.  I even tried flashing my stock EDID but that didn't work.

Ok so time to google and read over the code.  While I was going over your script I noticed that it differentiates between standard EDID's (128b) and ones with extension tables (256b).  And that made me go hmm and check ChalkElec's one... well sure enough it only writes 128b regardless of the size of the input file.  I'm assuming the EEPROM was left in a odd state because it was either not fully erased or half written with old data.

Anyway, enough rambling on my side.  The end of the story is I was able to reflash the EDID with your work and fixed my HDMI port.

Oh one more thing, no matter how I tried to flash the chip its contents didn't change.  I know that the EDID spec requires digital TV's to write protect the ROM, but then how the heck does that explain it breaking when trying to flash (and fixing it when flashing the Full old contents back).  *scratches head*

Thank-you for saving me from a heart attack,
Quad

_*For some reason Sony decided to make the first detailed timing 1080p and OS X doesn't want to do scaled resolutions without 2160p as a detailed resolution.  Yay Apple. >.<_

**Comment by bulletmark** [comment]
I wrote this little app many years ago to recover my screen which had a corrupted EDID. Since then I have only added small changes to cater for various requests raised here. Anyhow, thanks for the feedback that some people are still finding it useful!
