### ISSUE TITLE
Nothing changes after writing to Asus 22T1E via Nvidia GeForce 1050 Ti

### ISSUE THREAD

**Issue by timakro** [bulletmark/edid-rw#8]
```
# i2cdetect -l
i2c-3	i2c       	NVIDIA i2c adapter 4 at 1:00.0  	I2C adapter
i2c-1	smbus     	ddbridge                        	SMBus adapter
i2c-4	i2c       	NVIDIA i2c adapter 6 at 1:00.0  	I2C adapter
i2c-2	smbus     	ddbridge                        	SMBus adapter
i2c-0	smbus     	ddbridge                        	SMBus adapter
i2c-5	i2c       	NVIDIA i2c adapter 7 at 1:00.0  	I2C adapter
```

The correct one seems to be number 4:

```
# i2cdetect 4
WARNING! This program can confuse your I2C bus, cause data loss and worse!
I will probe file /dev/i2c-4.
I will probe address range 0x03-0x77.
Continue? [Y/n] 
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- -- 
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
30: -- -- -- -- -- -- -- 37 -- -- 3a -- -- -- -- -- 
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
50: 50 -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
70: -- -- -- -- -- -- -- --                         
```

Address 0x50 is present, I can read using your tool and get plausible data with `sudo ./edid-rw 4 | edid-decode`. When writing my modified data using `sudo ./edid-rw -w 4 <edid.bin` your tool doesn't report any errors. But when reading the data again nothing changed. Also tried to remove my monitor from power between writing and reading, didn't help.

Do you have any ideas why this doesn't work? Should I try to write the EDID to my monitor using another GPU?

**Comment by bulletmark** [comment]
This utility just writes to the file device and if the OS fails to do that then your should see an exception on your screen. Since you are not seeing that we can assume the write is proceeding successfully and thus perhaps your device is receiving but not storing the new EDID?

Sorry, I am not an expert in this stuff. I wrote this little utility many years ago for my own one-off use and then posted it here where it seems to have be off some value to various others.

**Comment by timakro** [comment]
Okay, thanks for having a look anyways. This issue is not related to your tool so I'll close this.

**Comment by timautin** [comment]
FWIW, I have the same problem trying to overwrite the EDID of a BlackMagic Teranex Mini HDMI to SDI 12G. Everything seems to be working, but when reading the value it's still the same.
